### ISSUE TITLE
Deleting a note creates a folder in the home directory

### ISSUE THREAD

**Issue by OzoneGameDev** [toolstack/Folio#134] opened 2024-06-28 12:03 UTC
When deleting a note, a folder named "~" is created in the user's home directory containing the following folders:

.var/app/com.toolstack.Folio/data/.trash/[notebook name]/[note name].md

I believe the .trash folder should be created in the .var directory in the user's home directory.

https://github.com/toolstack/Folio/assets/143538292/2870f497-a9a1-4bda-9b03-e7776ee64df8

**Comment by toolstack** [comment] 2024-06-28 13:41
Duplicate of #123, the fix has been committed, I just haven't had a chance to do the release yet.

**Closed by toolstack** 2024-06-28 13:41 UTC
