### ISSUE TITLE
"~" directory in home directory

### ISSUE THREAD

**Issue by RocketRide9** [toolstack/Folio#178] opened 2024-10-02 16:52 UTC
There is '~' folder in my home directory. Judging by it's content, it was created by this app.
```
 ~ tree -a '~'
~
└── .var
    └── app
        └── com.toolstack.Folio
            └── data
                └── .trash
                    ├── pile
                    │   └── something
                    ├── sss
                    └── TD
                        ├── something
                        ├── something
                        ├── something
                        └── something

9 directories, 5 files
 ~ pwd
/home/dell
```
_probably_ it wasn't mean to be here

**Comment by toolstack** [comment] 2024-10-02 23:14
Duplicate of #112.

**Closed** 2024-10-02 23:14 UTC
Labels: duplicate
