### ISSUE TITLE
Markdown seems to be broken 24.06

### ISSUE THREAD

**Issue by kuiperzone** [toolstack/Folio#59] opened 2024-03-16 19:45 UTC
Issues in markdown. Below

![image](https://github.com/toolstack/Folio/assets/17156238/64aac0b1-daa6-4286-aace-531fa9efd58a)

**Comment by toolstack** [comment] 2024-03-16 23:13
I don't seem to be able to reproduce the error, can you link me to a sample markdown file that you see the problem with?

**Comment by kuiperzone** [comment] 2024-03-17 00:07
Sure. Attached.

OS: Debian 12, Gnome, Wayland.

[Galera Cluster.md](https://github.com/toolstack/Folio/files/14625639/Galera.Cluster.md)


Screenshot below is of the same markdown but in the Paper app.

![image](https://github.com/toolstack/Folio/assets/17156238/ce3934d2-8e64-4879-8681-22eef2b0be69)

**Comment by toolstack** [comment] 2024-03-17 01:36
Thanks, it looks like it has something to do with the newer link formatting code, shouldn't be too hard to track down.

**Comment by toolstack** [comment] 2024-03-17 23:22
Tacked down the issue to a race condition in the bare url regex and how the error code handled it.  Should be fixed in next release.

**Closed** 2024-03-17 23:21 UTC
Labels: bug
