### ISSUE TITLE
Sort by most recent change

### ISSUE THREAD

**Issue by frandavid100** [toolstack/Folio#43] opened 2024-03-10 09:28 UTC
Notes are currently sorted by creation date, which is not very useful when a note is very old but also very frequently used.  There should be an option to have the most recently used notes at the top of the list.

**Comment by toolstack** [comment] 2024-03-10 14:37
Notes are currently sorted by modified time, not creation time, so this is already the behaviour.

Also, duplicate of #32

**Closed** 2024-03-10 14:37 UTC
Labels: duplicate

**Comment by frandavid100** [comment] 2024-03-10 14:58
I was probably hit by #33.

**Comment by toolstack** [comment] 2024-03-10 15:01
Could be, 33 should be fixed in the next release, which should be out in the next week or so.

Selecting another notebook and then coming back to the current one will work around the issue until the fix is out.
