### ISSUE TITLE
Weird unremovable notebook

### ISSUE THREAD

**Issue by somepaulo** [toolstack/Folio#133] opened 2024-06-24 04:57 UTC
Just installed the app from Flathub, and it opened with a notebook already in it with the name `themes` that cannot be deleted. I can delete the folder through Nautilus, but every time I restart the app the folder is recreated and the notebook appears in the app. Renaming it or adding a note to it is also impossible. I can create other notebooks just fine and add notes to them.

Launching from terminal and trying to delete the notebook gives me the following errors:
```sh
(com.toolstack.Folio:2): GLib-GIO-CRITICAL **: 05:11:34.552: GFileInfo created without standard::display-name
(com.toolstack.Folio:2): GLib-GIO-CRITICAL **: 05:11:34.552: file ../gio/gfileinfo.c: line 1721 (g_file_info_get_display_name): should not be reached
** (com.toolstack.Folio:2): CRITICAL **: 05:11:34.552: string_to_string: assertion 'self != NULL' failed
```

![Screenshot from 2024-06-24 05-48-26](https://github.com/toolstack/Folio/assets/15643750/059a1090-5b11-4028-8702-42573a948b85)
![Screenshot from 2024-06-24 05-48-40](https://github.com/toolstack/Folio/assets/15643750/0b3471e2-560e-4099-8562-7ae82b869597)
![Screenshot from 2024-06-24 05-49-11-obfuscated](https://github.com/toolstack/Folio/assets/15643750/ad788ca0-d075-4cf5-abee-3588d63be7ad)

**Comment by toolstack** [comment] 2024-06-24 13:13
Duplicate of #123, the fix has been committed, I just haven't had a chance to do the release yet.

**Closed by toolstack** 2024-06-24 13:13 UTC
Labels: duplicate
