### ISSUE TITLE
Feat: Tray icon feature

### ISSUE THREAD

**Issue by AmreeshTyagi** [toolstack/Folio#227] opened 2024-11-17 12:47 UTC
Really a wonderful and useful app. I am using Notes on Mac, but this app on my Ubuntu system is very intuitive than Mac notes. 

Would be good if you can provide tray icon feature fir the same.

**Comment by toolstack** [comment] 2024-11-17 16:25
Duplicate of #153 

Gnome no longer supports tray icons so Folio won't be either.

**Closed by toolstack** 2024-11-17 16:25 UTC
Labels: enhancement, wontfix
